[versions]
versionName = "0.1.1"

kotlin = "1.9.24"
dokkaVersion = "1.8.20"
jupiter = "5.10.0"
jupiterPlatform = "1.10.0"

[libraries]

jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jupiter" }
jupiter-platform = { module = "org.junit.platform:junit-platform-suite", version.ref = "jupiterPlatform" }

[bundles]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokkaVersion" }